spring:
  datasource:
    url: localhost
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 11111
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
server:
  servlet:
    encoding:
      force-response: true